# Generated by Django 3.0.7 on 2020-06-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs_app', '0002_auto_20200607_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient_deleted_at',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Receiver deleted at'),
        ),
    ]
