# Generated by Django 3.0.7 on 2020-06-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs_app', '0003_auto_20200607_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='parent_msg',
        ),
        migrations.RemoveField(
            model_name='message',
            name='replied_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_deleted_at',
        ),
        migrations.AddField(
            model_name='message',
            name='sender_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver_deleted_at',
            field=models.BooleanField(default=False),
        ),
    ]
