# Generated by Django 3.0.7 on 2020-06-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs_app', '0004_auto_20200610_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver_deleted_at',
            new_name='receiver_deleted',
        ),
    ]
