# Generated by Django 3.0.7 on 2020-06-10 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs_app', '0005_auto_20200610_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-id'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
